---
# vim: set ft=ansible:

- name: Enabling Chrony NTP for SNO
  k8s:
    state: present
    kubeconfig: /root/sno-{{ item }}/auth/kubeconfig
    definition: "{{ lookup('file', 'masters-chrony-configuration.yaml') }}"
  register: ntp_success
  retries: 20
  delay: 30
  until: ntp_success is not failed
  loop:
    - rhacm
    - edge1
    - edge2
