---
# vim: set ft=ansible:

- name: Enabling image registry
  k8s:
    state: present
    kubeconfig: /root/sno-{{ item }}/auth/kubeconfig
    definition: "{{ lookup('file', 'image-registry.yaml') }}"
  register: imgreg_success
  retries: 20
  delay: 30
  until: imgreg_success is not failed
  loop:
    - rhacm
    - edge1
    - edge2
